/**
 * Seed Data - Default Customers and Work Types
 * Ported from src/js/data.js
 */

import type { Customer, WorkType, CommissionWorker } from '@/types';

export const defaultCustomers: Customer[] = [
  // Fixed Monthly Clients
  {
    id: 1,
    name: 'Ramani Motors',
    shortCode: 'RMP',
    type: 'Monthly',
    hasCommission: true,
    requiresDc: true,
    notes: 'Mahindra vehicles',
    isActive: true,
  },
  {
    id: 2,
    name: 'Ramani Cars',
    shortCode: 'WW',
    type: 'Monthly',
    hasCommission: true,
    requiresDc: true,
    notes: 'Volkswagen vehicles',
    isActive: true,
  },
  {
    id: 3,
    name: 'Wagen Autos',
    shortCode: 'WP',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: true,
    notes: 'Multi-brand',
    isActive: true,
  },
  {
    id: 4,
    name: 'N Mahalingam',
    shortCode: 'NM',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 5,
    name: 'Friends Motors',
    shortCode: 'FDS',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 6,
    name: 'Vails Pradeep',
    shortCode: 'Vails',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 7,
    name: 'Sree Cars (P)',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 8,
    name: 'Sree Cars (U)',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 9,
    name: 'Ford Arun',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 10,
    name: 'A. Siva',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 11,
    name: 'TMJ Mayil',
    shortCode: 'TMJ',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 12,
    name: 'Alfa',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 13,
    name: 'Karunamoorthi',
    shortCode: 'KM',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 14,
    name: 'Anandaraman',
    shortCode: '',
    type: 'Monthly',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  // Invoice-Based Clients
  {
    id: 15,
    name: 'Ayangaran',
    shortCode: '',
    type: 'Invoice',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 16,
    name: 'MyTVS (Poo)',
    shortCode: '',
    type: 'Invoice',
    hasCommission: false,
    requiresDc: false,
    notes: '',
    isActive: true,
  },
  {
    id: 17,
    name: 'AKR',
    shortCode: 'AKR',
    type: 'Invoice',
    hasCommission: true,
    requiresDc: true,
    notes: 'High risk - can delay',
    isActive: true,
  },
  {
    id: 18,
    name: 'AVP',
    shortCode: 'AVP',
    type: 'Invoice',
    hasCommission: true,
    requiresDc: true,
    notes: 'High risk - can delay',
    isActive: true,
  },
  // Party-Credit (Known individuals) - abbreviated for space
  { id: 19, name: 'Ooty Raj', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 20, name: 'SK Sathish', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 21, name: 'Sreenivasan', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 22, name: 'Ford Diamond', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 23, name: 'Kunnathoor', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 24, name: 'New Busstand', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 25, name: 'Ajmeerbhai', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 26, name: 'SK Saravanan', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 27, name: 'SRT Vinoth', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 28, name: 'Dravid', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 29, name: 'Akhila Hari', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 30, name: 'Akhila Senthil', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 31, name: 'Diamond (M)', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 32, name: 'Kumar (P)', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 33, name: 'KGV', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 34, name: 'Cuttubai', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 35, name: 'Prabhu', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 36, name: 'Ajith', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 37, name: 'Guhan', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 38, name: 'Velusamy', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 39, name: 'City Cars', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 40, name: 'D2C', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 41, name: 'Ooty Hindi', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 42, name: 'Rahul', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 43, name: 'Meenakshi', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 44, name: 'Sabari', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 45, name: 'Gnanaprakash', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 46, name: 'Ayyan Spares', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 47, name: 'Jeeva', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 48, name: 'Sivakumar', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 49, name: 'Kathir', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 50, name: 'PS Auto', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 51, name: 'Palanisamy', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 52, name: 'Prabhakaran', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 53, name: 'Karuppu', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  { id: 54, name: 'Elite', shortCode: '', type: 'Party-Credit', hasCommission: false, requiresDc: false, notes: '', isActive: true },
  // Anonymous Party (Walk-in)
  {
    id: 100,
    name: 'Party',
    shortCode: '',
    type: 'Cash',
    hasCommission: false,
    requiresDc: false,
    notes: 'Walk-in customer',
    isActive: true,
  },
];

export const defaultWorkTypes: WorkType[] = [
  // Skimming Services
  { id: 1, category: 'Skimming', name: 'Rotor Skimming', shortCode: '', defaultUnit: 'Per set of 2', defaultRate: 500 },
  { id: 2, category: 'Skimming', name: 'Drum Skimming', shortCode: '', defaultUnit: 'Per set of 2', defaultRate: 300 },
  { id: 3, category: 'Skimming', name: 'Flywheel Skimming', shortCode: '', defaultUnit: 'Per piece', defaultRate: 500 },
  { id: 4, category: 'Skimming', name: 'Flywheel Preplate Throwing', shortCode: '', defaultUnit: 'Per piece', defaultRate: 0 },
  { id: 5, category: 'Skimming', name: 'Flywheel Ring', shortCode: '', defaultUnit: 'Per piece', defaultRate: 200 },
  // Pressing — Bearings
  { id: 6, category: 'Bearing', name: 'Drum Bearing', shortCode: 'DB', defaultUnit: 'Per bearing', defaultRate: 100 },
  { id: 7, category: 'Bearing', name: 'Disc Bearing', shortCode: '', defaultUnit: 'Per bearing', defaultRate: 100 },
  { id: 8, category: 'Bearing', name: 'Hub Bearing', shortCode: '', defaultUnit: 'Per bearing', defaultRate: 100 },
  { id: 9, category: 'Bearing', name: 'Axle Bearing', shortCode: 'AB', defaultUnit: 'Per bearing', defaultRate: 150 },
  { id: 10, category: 'Bearing', name: 'Crown Bearing', shortCode: '', defaultUnit: 'Per bearing', defaultRate: 100 },
  { id: 11, category: 'Bearing', name: 'End Bearing', shortCode: '', defaultUnit: 'Per bearing', defaultRate: 100 },
  { id: 12, category: 'Bearing', name: 'Outer Bearing', shortCode: 'OB', defaultUnit: 'Per bearing', defaultRate: 150 },
  { id: 13, category: 'Bearing', name: 'Wheel Bearing', shortCode: '', defaultUnit: 'Per bearing', defaultRate: 300 },
  // Pressing — Bushes
  { id: 14, category: 'Bush', name: 'Lower Arm Bush', shortCode: 'LA', defaultUnit: 'Per set', defaultRate: 300 },
  { id: 15, category: 'Bush', name: 'Upper Arm Bush', shortCode: 'UA', defaultUnit: 'Per set', defaultRate: 400 },
  { id: 16, category: 'Bush', name: 'Collar Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 150 },
  { id: 17, category: 'Bush', name: 'Chase Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 18, category: 'Bush', name: 'Center Bed Bush', shortCode: 'C-Bed', defaultUnit: 'Per bush', defaultRate: 200 },
  { id: 19, category: 'Bush', name: 'General Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 20, category: 'Bush', name: 'End Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 21, category: 'Bush', name: 'Gearbox Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 22, category: 'Bush', name: 'Spring Cut Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 23, category: 'Bush', name: 'Subframe Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  { id: 24, category: 'Bush', name: 'Bed Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 150 },
  { id: 25, category: 'Bush', name: 'Aluminum Bed Bush', shortCode: '', defaultUnit: 'Per bush', defaultRate: 100 },
  // Driveshaft & Steering
  { id: 26, category: 'Driveshaft', name: 'Driveshaft Removing', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 27, category: 'Driveshaft', name: 'Driveshaft Threading', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 28, category: 'Driveshaft', name: 'Driveshaft Cleaning', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 29, category: 'Driveshaft', name: 'Driveshaft Combo', shortCode: '', defaultUnit: 'Per piece', defaultRate: 300 },
  { id: 30, category: 'Driveshaft', name: 'Steering Box Bracket', shortCode: '', defaultUnit: 'Per job', defaultRate: 200 },
  { id: 31, category: 'Driveshaft', name: 'Kingpin — Normal', shortCode: '', defaultUnit: 'Per job', defaultRate: 1200 },
  { id: 32, category: 'Driveshaft', name: 'Kingpin — Traveler', shortCode: '', defaultUnit: 'Per job', defaultRate: 1600 },
  { id: 33, category: 'Driveshaft', name: 'Kingpin — Dhosthbada', shortCode: '', defaultUnit: 'Per job', defaultRate: 1600 },
  // Bolts & Threading
  { id: 34, category: 'Bolt', name: 'Silencer Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 150 },
  { id: 35, category: 'Bolt', name: 'Sensor Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 36, category: 'Bolt', name: 'Bed Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 37, category: 'Bolt', name: 'Bracket Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 38, category: 'Bolt', name: 'Sump Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 39, category: 'Bolt', name: 'Center Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 40, category: 'Bolt', name: 'Gear Box Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 41, category: 'Bolt', name: 'Oil Nut', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 42, category: 'Bolt', name: 'Engine Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 100 },
  { id: 43, category: 'Bolt', name: 'Turbo Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 150 },
  { id: 44, category: 'Bolt', name: 'Wheel Bolt', shortCode: '', defaultUnit: 'Per bolt', defaultRate: 400 },
  { id: 45, category: 'Bolt', name: 'Stud', shortCode: '', defaultUnit: 'Per stud', defaultRate: 100 },
  { id: 46, category: 'Bolt', name: 'Thread Sleeve M6', shortCode: 'M6', defaultUnit: 'Per sleeve', defaultRate: 150 },
  { id: 47, category: 'Bolt', name: 'Thread Sleeve M8', shortCode: 'M8', defaultUnit: 'Per sleeve', defaultRate: 200 },
  { id: 48, category: 'Bolt', name: 'Thread Sleeve M10', shortCode: 'M10', defaultUnit: 'Per sleeve', defaultRate: 250 },
  { id: 49, category: 'Bolt', name: 'Thread Sleeve M12', shortCode: 'M12', defaultUnit: 'Per sleeve', defaultRate: 500 },
  { id: 50, category: 'Bolt', name: 'Thread Sleeve M14', shortCode: 'M14', defaultUnit: 'Per sleeve', defaultRate: 350 },
  // Welding
  { id: 51, category: 'Welding', name: 'Welding Works', shortCode: '', defaultUnit: 'Per job', defaultRate: 200 },
  { id: 52, category: 'Welding', name: 'S-Welding', shortCode: '', defaultUnit: 'Per job', defaultRate: 200 },
  { id: 53, category: 'Welding', name: 'Silencer Welding', shortCode: '', defaultUnit: 'Per job', defaultRate: 150 },
  // Other Services
  { id: 54, category: 'Other', name: 'Clutch Pedal', shortCode: '', defaultUnit: 'Per job', defaultRate: 200 },
  { id: 55, category: 'Other', name: 'Joint Star', shortCode: '', defaultUnit: 'Per piece', defaultRate: 300 },
  { id: 56, category: 'Other', name: 'Caliper Nipple', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 57, category: 'Other', name: 'Spindle Threading', shortCode: '', defaultUnit: 'Per piece', defaultRate: 100 },
  { id: 58, category: 'Other', name: 'Compressor Switch', shortCode: '', defaultUnit: 'Per piece', defaultRate: 400 },
  { id: 59, category: 'Other', name: 'Sensor Remove', shortCode: '', defaultUnit: 'Per job', defaultRate: 300 },
  { id: 60, category: 'Other', name: 'Hub Remove', shortCode: '', defaultUnit: 'Per hub', defaultRate: 200 },
  { id: 61, category: 'Other', name: 'Gearbox Setting', shortCode: '', defaultUnit: 'Per job', defaultRate: 500 },
  { id: 62, category: 'Other', name: 'Sump Thread and Bolt', shortCode: '', defaultUnit: 'Per job', defaultRate: 600 },
  { id: 63, category: 'Other', name: 'Other / Miscellaneous', shortCode: '', defaultUnit: 'Per job', defaultRate: 0 },
];

// Commission Workers - default distribution for commission customers
export const defaultCommissionWorkers: CommissionWorker[] = [
  // RMP (Ramani Motors) - id: 1
  { id: 1, customerId: 1, name: 'Raja', shareType: 'percentage', shareValue: 40, isActive: true },
  { id: 2, customerId: 1, name: 'Bhai', shareType: 'percentage', shareValue: 40, isActive: true },
  { id: 3, customerId: 1, name: 'PersonXX', shareType: 'percentage', shareValue: 20, isActive: true },
  // WW (Ramani Cars) - id: 2
  { id: 4, customerId: 2, name: 'Person1', shareType: 'percentage', shareValue: 50, isActive: true },
  { id: 5, customerId: 2, name: 'Person2', shareType: 'percentage', shareValue: 30, isActive: true },
  { id: 6, customerId: 2, name: 'Person3', shareType: 'percentage', shareValue: 20, isActive: true },
  // AKR - id: 17
  { id: 7, customerId: 17, name: 'Commission Person', shareType: 'percentage', shareValue: 100, isActive: true },
  // AVP - id: 18
  { id: 8, customerId: 18, name: 'Commission Person', shareType: 'percentage', shareValue: 100, isActive: true },
];
