services:
  adminer:
    image: adminer:4
    container_name: slw-adminer
    restart: unless-stopped
    ports:
      - '8081:8080'
    depends_on:
      postgres:
        condition: service_healthy
